# Excavator auto-updates this file. Please contribute improvements to the central template:
# https://github.palantir.build/foundry/standards/blob/develop/excavator/excavator-config/templates/excavator.yml.template

auto-label:
  names:
    versions-props/upgrade-all: [ "merge when ready" ]
  tags:
    roomba: [ "merge when ready" ]
    swiffer: [ "merge when ready" ]
    automerge: [ "merge when ready" ]
    standards: [ "merge when ready" ]
    autorelease: [ "autorelease" ]
