com.fasterxml.jackson.core:jackson-databind = 2.16.1
com.palantir.conjure.java.runtime:* = 8.28.0
com.palantir.safe-logging:* = 3.9.0
com.fasterxml.jackson.*:* = 2.16.1
com.amazonaws:aws-athena-federation-sdk = 2025.46.1
com.amazonaws:aws-lambda-java-log4j2 = 1.5.1
com.palantir.conjure:conjure = 4.48.0
com.palantir.conjure.java:* = 8.66.0
com.palantir.conjure.java.api:test-utils = 2.67.0
com.palantir.dialogue:* = 6.17.0
org.apache.logging.log4j:* = 2.24.0
org.junit.jupiter:* = 6.0.1
org.assertj:assertj-core = 3.27.6
org.mockito:* = 5.21.0

# dependency-upgrader:OFF
# need to keep arrow version in sync with federation connector
org.apache.arrow:* = 3.0.0
# dependency-upgrader:ON

