com.fasterxml.jackson.core:jackson-databind = 2.21.1
com.palantir.conjure.java.runtime:* = 8.37.0
com.palantir.safe-logging:* = 3.16.0
com.fasterxml.jackson.*:* = 2.16.1
com.amazonaws:aws-athena-federation-sdk = 2026.24.1
com.amazonaws:aws-lambda-java-log4j2 = 1.6.2
com.palantir.conjure:conjure = 4.57.0
com.palantir.conjure.java:* = 8.80.0
com.palantir.conjure.java.api:test-utils = 2.74.0
com.palantir.dialogue:* = 6.31.0
org.apache.logging.log4j:* = 2.24.0
org.junit.jupiter:* = 6.1.0
org.assertj:assertj-core = 3.27.7
org.mockito:* = 5.23.0

# dependency-upgrader:OFF
# need to keep arrow version in sync with federation connector
org.apache.arrow:* = 3.0.0
# dependency-upgrader:ON

